kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argocd-learning
nodes:
- role: control-plane
  image: kindest/node:v1.32.11@sha256:5fc52d52a7b9574015299724bd68f183702956aa4a2116ae75a63cb574b35af8
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # ArgoCD Server
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  # ArgoCD gRPC
  - containerPort: 30443
    hostPort: 30443
    protocol: TCP
  # Apps
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  - containerPort: 30002
    hostPort: 30002
    protocol: TCP
- role: worker
  image: kindest/node:v1.32.11@sha256:5fc52d52a7b9574015299724bd68f183702956aa4a2116ae75a63cb574b35af8
  labels:
    workload: applications
- role: worker
  image: kindest/node:v1.32.11@sha256:5fc52d52a7b9574015299724bd68f183702956aa4a2116ae75a63cb574b35af8
  labels:
    workload: applications
